CREATE TABLE IF NOT EXISTS public.accounts (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    balance numeric(38, 2) NULL,
    user_id BIGINT NULL,
    initial_balance numeric(38, 2) NOT NULL,
	CONSTRAINT accounts_pkey PRIMARY KEY (id),
	CONSTRAINT uke4w4av1wrhanry7t6mxt42nou UNIQUE (user_id),
	CONSTRAINT fknjuop33mo69pd79ctplkck40n FOREIGN KEY (user_id) REFERENCES public.users(id)
);